FROM ubuntu

## DO NOT FORGET TO INCLUEDE  MAXMIND_LICENSE_KEY environment variable
# otherwise it may fail for lookup test cases

RUN apt-get update && apt-get install -y python3 python3-pip

COPY requirements.txt /richkit/requirements.txt

COPY richkit /richkit/richkit

COPY .git /richkit/.git

RUN pip3 install -r /richkit/requirements.txt

RUN pip3 install coverage pytest sphinx flake8

COPY .github/local-test/run-test.sh /richkit/richkit/run-test.sh

CMD ["/richkit/richkit/run-test.sh"]


